dist: xenial

language: go
go:
  - "1.12.x"

go_import_path: github.com/hawell/redins

git:
  depth: 1

branches:
  only:
  - master

before_install:
  - sudo systemctl restart redis-server
  - echo "127.0.0.1 redis" |  sudo tee -a /etc/hosts > /dev/null
  - mkdir -p $GOPATH/src/hawell/
  - ln -sf `pwd` $GOPATH/src/hawell/redins
  - cd $GOPATH/src/hawell/redins

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
